# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/modiacontextholder
team: oppfolging
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
webproxy: true
healthcheck:
  liveness:
    path: modiacontextholder/internal/isAlive
    initialDelay: 60
  readiness:
    path: modiacontextholder/internal/selftest
    initialDay: 60
prometheus:
  enabled: true
  path: modiacontextholder/internal/metrics
resources:
  limits:
    cpu: 3000m
    memory: 768Mi
  requests:
    cpu: 200m
    memory: 512Mi
fasitResources:
  used:
    - alias: srvmodiacontextholder
      resourceType: credential
    - alias: securityTokenService
      resourceType: baseurl
    - alias: loadbalancer:modiacontextholder
      resourceType: loadbalancerconfig
    - alias: loadbalancer:modiacontextholder-modapp
      resourceType: loadbalancerconfig
    - alias: veilarblogin.redirect-url
      resourceType: restservice
      propertyMap:
        url: OIDC_REDIRECT_URL
    - alias: modiacontextholderDB
      resourceType: datasource

    # ISSO
    - alias: isso-host
      resourceType: baseurl
    - alias: isso-jwks
      resourceType: baseurl
    - alias: isso-issuer
      resourceType: baseurl
    - alias: isso.isalive
      resourceType: baseurl
    - alias: isso-rp-user
      resourceType: credential

    # Appdynamics
    - alias: appdynamics
      resourceType: applicationProperties

  exposed:
    - alias: veiledercontext-isalive
      resourceType: restservice
      path: /modiacontextholder/internal/isAlive
    - alias: veiledercontext-api
      resourceType: restservice
      path: /modiacontextholder/api/veiledercontext
    - alias: events-api
      resourceType: restservice
      path: /modiacontextholder/api/events
