---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: modiacontextholder
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  readiness:
    path: internal/isReady
    initialDelay: 50
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 768Mi
  ingresses:
    - https://modiacontextholder.intern.dev.nav.no
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: modiacontextholder-db
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    outbound:
      external:
        - host: personoversikt-unleash-api.nav.cloud.nais.io
        - host: axsys.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: norg2.dev-fss-pub.nais.io
      rules:
        - application: modiacontextholder-redis-med-passord
        - application: nom-api
          namespace: nom
          cluster: dev-gcp
    inbound:
      rules:
        - application: arbeidssokerregistrering-veileder
          namespace: paw
          cluster: dev-gcp
        - application: arbeidssokerregistrering-for-veileder
          cluster: dev-gcp
          namespace: paw
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: dev-gcp
        - application: beslutteroversikt
          namespace: obo
          cluster: dev-gcp
        - application: smregistrering
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmmanuell
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syk-dig
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: modiaflatefs-{{ namespace }}
          namespace: personoversikt
          cluster: dev-fss
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: dev-gcp
        - application: modiapersonoversikt-{{ namespace }}
          namespace: personoversikt
          cluster: dev-fss
        - application: rekrutteringsbistand-kandidatsok-api
          namespace: toi
          cluster: dev-gcp
        - application: rekrutteringsbistand
          namespace: toi
          cluster: dev-gcp
        - application: spinnsyn-frontend-interne
          namespace: flex
          cluster: dev-gcp
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomoteoversikt
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: sosialhjelp-modia-oidc-auth-proxy
          namespace: teamdigisos
          cluster: dev-fss
        - application: speil
          namespace: tbd
          cluster: dev-gcp
        - application: modiacontextholder-q1
          namespace: personoversikt
          cluster: dev-fss
        - application: modiacontextholder-q2
          namespace: personoversikt
          cluster: dev-fss
  secureLogs:
    enabled: true
  envFrom:
    - secret: modiacontextholder-unleash-api-token
    - secret: modiacontextholder-redis-passord
  env:
    - name: AXSYS_URL
      value: "https://axsys.dev-fss-pub.nais.io"
    - name: AXSYS_SCOPE
      value: "dev-fss:org:axsys"
    - name: PDL_API_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "dev-fss:pdl:pdl-api"
    - name: NORG2_API_URL
      value: "https://norg2.dev-fss-pub.nais.io/norg2"
    - name: NORG2_SCOPE
      value: "dev-fss:org:norg2"
    - name: NOM_URL
      value: "https://nom-api.intern.dev.nav.no"
    - name: NOM_SCOPE
      value: "dev-gcp:nom:nom-api"
    - name: MS_GRAPH_URL
      value: "https://graph.microsoft.com/"
    - name: MS_GRAPH_SCOPE
      value: "https://graph.microsoft.com/.default"
    - name: APP_ENVIRONMENT_NAME
      value: "{{ namespace }}"
    - name: AAREG_URL
      value: "https://arbeid-og-inntekt-q2.dev-fss-pub.nais.io"
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_HOST
      value: "modiacontextholder-redis-med-passord.personoversikt.svc.cluster.local"
    - name: SALESFORCE_URL
      value: "https://navdialog--sit2.lightning.force.com"
    - name: DB_NAME
      value: "modiacontextholder-db"
    - name: UNLEASH_ENVIRONMENT
      value: "development"
    # MODIACONTEXTHOLDER_PROXY_* er ikke brukt i GCP
    - name: MODIACONTEXTHOLDER_PROXY_API_URL
      value: "https://modiacontextholder.intern.dev.nav.no"
    - name: MODIACONTEXTHOLDER_PROXY_API_SCOPE
      value: "dev-gcp:personoversikt:modiacontextholder"
