---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: modiacontextholder
  namespace: personoversikt
  labels:
    team: personoversikt
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  image: "{{ image }}"
  port: 4000
  liveness:
    path: internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  readiness:
    path: internal/isReady
    initialDelay: 50
    periodSeconds: 10
    timeout: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  ingresses:
    - https://modiacontextholder.intern.dev.nav.no
    - https://modiacontextholder.ansatt.dev.nav.no
  replicas:
    min: 2
    max: 4
    scalingStrategy:
      cpu:
        thresholdPercentage: 50
  redis:
    - instance: contextholder
      access: readwrite
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
  accessPolicy:
    outbound:
      external:
        - host: personoversikt-unleash-api.nav.cloud.nais.io
        - host: axsys.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: graph.microsoft.com
      rules:
        - application: nom-api
          namespace: nom
          cluster: dev-gcp
        - application: norg2
          namespace: org
    inbound:
      rules:
        - application: arbeidssokerregistrering-for-veileder
          cluster: dev-gcp
          namespace: paw
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: dev-gcp
        - application: beslutteroversikt
          namespace: obo
          cluster: dev-gcp
        - application: syfosmmanuell
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syk-dig
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: modiaflatefs-{{ namespace }}
          namespace: personoversikt
          cluster: dev-fss
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: dev-gcp
        - application: modiapersonoversikt-{{ namespace }}
          namespace: personoversikt
          cluster: dev-fss
        - application: rekrutteringsbistand-kandidatsok-api
          namespace: toi
          cluster: dev-gcp
        - application: rekrutteringsbistand
          namespace: toi
          cluster: dev-gcp
        - application: rekrutteringsbistand-frontend
          namespace: toi
        - application: spinnsyn-frontend-interne
          namespace: flex
          cluster: dev-gcp
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomoteoversikt
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: sosialhjelp-modia-oidc-auth-proxy
          namespace: teamdigisos
          cluster: dev-fss
        - application: speil
          namespace: tbd
          cluster: dev-gcp
        - application: tiltaksgjennomforing-intern
          namespace: arbeidsgiver
          cluster: dev-gcp
        - application: tiltak-refusjon-saksbehandler
          namespace: arbeidsgiver
          cluster: dev-gcp
  secureLogs:
    enabled: true
  envFrom:
    - secret: modiacontextholder-unleash-api-token
  env:
    - name: AXSYS_URL
      value: "https://axsys.dev-fss-pub.nais.io"
    - name: AXSYS_SCOPE
      value: "dev-fss:org:axsys"
    - name: PDL_API_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "dev-fss:pdl:pdl-api"
    - name: NORG2_API_URL
      value: "http://norg2.org/norg2"
    - name: NORG2_SCOPE
      value: "dev-gcp:org:norg2"
    - name: NOM_URL
      value: "https://nom-api.intern.dev.nav.no"
    - name: NOM_SCOPE
      value: "dev-gcp:nom:nom-api"
    - name: MS_GRAPH_URL
      value: "https://graph.microsoft.com/"
    - name: MS_GRAPH_SCOPE
      value: "https://graph.microsoft.com/.default"
    - name: APP_ENVIRONMENT_NAME
      value: "q2"
    - name: AAREG_URL
      value: "https://arbeid-og-inntekt-q2.dev-fss-pub.nais.io"
    - name: AAREG_PUBLIC_URL
      value: "https://arbeid-og-inntekt-q2.dev.adeo.no"
    - name: SALESFORCE_URL
      value: "https://navdialog--sit2.lightning.force.com"
    - name: UNLEASH_ENVIRONMENT
      value: "development"
