---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: modiacontextholder
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{ image }}"
  port: 8080
  webproxy: true
  liveness:
    path: modiacontextholder/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: modiacontextholder/internal/prometheus
  readiness:
    path: modiacontextholder/internal/isReady
    initialDelay: 50
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 768Mi
  ingresses:
    - https://modiacontextholder.prod-fss-pub.nais.io/modiacontextholder
    - https://modiacontextholder.intern.nav.no/modiacontextholder
    - https://modiacontextholder.nais.adeo.no/modiacontextholder
    - https://modapp.adeo.no/modiacontextholder
    - https://app.adeo.no/modiacontextholder
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvmodiacontextholder
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/prod/srvssolinux
        mountPath: /var/run/secrets/nais.io/srvssolinux
      - kvPath: /oracle/data/prod/creds/modiacontextholder-user
        mountPath: /var/run/secrets/nais.io/modiacontextholderDB
      - kvPath: /oracle/data/prod/config/modiacontextholder
        mountPath: /var/run/secrets/nais.io/db_config
      - kvPath: /apikey/appdynamics/prod
        mountPath: /var/run/secrets/nais.io/vault
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: arbeidssokerregistrering-veileder
          namespace: paw
          cluster: prod-gcp
        - application: arbeidssokerregistrering-for-veileder
          cluster: prod-gcp
          namespace: paw
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: prod-gcp
        - application: beslutteroversikt
          namespace: obo
          cluster: prod-gcp
        - application: smregistrering
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmmanuell
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syk-dig
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: modiaflatefs
          namespace: personoversikt
          cluster: prod-fss
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: prod-fss
        - application: rekrutteringsbistand-container
          namespace: toi
          cluster: prod-gcp
        - application: rekrutteringsbistand
          namespace: toi
          cluster: prod-gcp
        - application: spinnsyn-frontend-interne
          namespace: flex
          cluster: prod-gcp
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfomoteoversikt
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: sosialhjelp-modia-oidc-auth-proxy
          namespace: teamdigisos
          cluster: prod-fss
  secureLogs:
    enabled: true
  env:
    - name: SECURITY_TOKEN_SERVICE_DISCOVERY_URL
      value: "https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration"
    - name: AXSYS_REST_API_URL
      value: "https://axsys.nais.adeo.no"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.io/api/"
    - name: PDL_API_URL
      value: "https://pdl-api.nais.adeo.no/graphql"
    - name: NORG2_API_URL
      value: "https://app.adeo.no/norg2"
    - name: LDAP_BASEDN
      value: "dc=adeo,dc=no"
    - name: LDAP_URL
      value: "ldaps://ldapgw.adeo.no"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=adeo,dc=no"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=adeo,dc=no"
    - name: LDAP_DOMAIN
      value: "ADEO.NO"
    - name: MS_GRAPH_CLIENT_URL
      value: "https://graph.microsoft.com/v1.0"
    - name: LOGINSERVICE_OIDC_DISCOVERYURI
      value: "https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration"
    - name: AAD_V2_DISCOVERURI
      value: "https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration"
    - name: LOGINSERVICE_OIDC_CLIENTID
      value: "9b4e07a3-4f4c-4bab-b866-87f62dff480d"
    - name: APP_ENVIRONMENT_NAME
      value: "p"
    - name: AAREG_URL
      value: "https://arbeid-og-inntekt.nais.adeo.no"
    - name: REDIS_HOST
      value: "modiacontextholder-redis.personoversikt.svc.nais.local"
    - name: SALESFORCE_URL
      value: "https://navdialog.lightning.force.com"
