---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: modiacontextholder
  namespace: default
  labels:
    team: personoversikt
spec:
  image: "{{ image }}"
  port: 8080
  webproxy: true
  liveness:
    path: modiacontextholder/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: modiacontextholder/internal/prometheus
  readiness:
    path: modiacontextholder/internal/isReady
    initialDelay: 50
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 768Mi
  ingresses:
    - https://modiacontextholder.intern.nav.no/modiacontextholder
    - https://modiacontextholder.nais.adeo.no/modiacontextholder
    - https://modapp.adeo.no/modiacontextholder
    - https://app.adeo.no/modiacontextholder
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvmodiacontextholder
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/prod/srvssolinux
        mountPath: /var/run/secrets/nais.io/srvssolinux
      - kvPath: /oracle/data/prod/creds/modiacontextholder-user
        mountPath: /var/run/secrets/nais.io/modiacontextholderDB
      - kvPath: /oracle/data/prod/config/modiacontextholder
        mountPath: /var/run/secrets/nais.io/db_config
      - kvPath: /apikey/appdynamics/prod
        mountPath: /var/run/secrets/nais.io/vault
  secureLogs:
    enabled: true
  env:
    - name: SECURITY_TOKEN_SERVICE_DISCOVERY_URL
      value: "https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration"
    - name: AXSYS_REST_API_URL
      value: "https://axsys.nais.adeo.no"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.io/api/"
    - name: PDL_API_URL
      value: "https://pdl-api.nais.adeo.no/graphql"
    - name: NORG2_API_URL
      value: "https://app.adeo.no/norg2"
    - name: LDAP_BASEDN
      value: "dc=adeo,dc=no"
    - name: LDAP_URL
      value: "ldaps://ldapgw.adeo.no"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=adeo,dc=no"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=adeo,dc=no"
    - name: LDAP_DOMAIN
      value: "ADEO.NO"
    - name: MS_GRAPH_CLIENT_URL
      value: "https://graph.microsoft.com/v1.0"
    - name: ISSO_CLIENT_ID
      value: "veilarblogin-p"
    - name: MODIA_CLIENT_ID
      value: "modialogin-p"
    - name: FPSAK_CLIENT_ID
      value: "fpsak-frontend-p"
    - name: ISSO_DISCOVERY_URL
      value: "https://isso.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: LOGINSERVICE_OIDC_DISCOVERYURI
      value: "https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration"
    - name: AAD_V2_DISCOVERURI
      value: "https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration"
    - name: LOGINSERVICE_OIDC_CLIENTID
      value: "9b4e07a3-4f4c-4bab-b866-87f62dff480d"
    - name: VEILARBLOGIN_AAD_CLIENT_ID
      value: "109c7064-47c9-4e34-b735-8cdc0d383cc1"
    - name: SYFO_FINNFASTLEGE_CLIENTID
      value: "916a8191-f241-4227-be1a-4b820657254f"
    - name: SYFO_SYFOMODIAPERSON_CLIENTID
      value: "a04bb3b5-8051-40bb-a5f0-f9f4a409b07a"
    - name: SYFO_SYFOMOTEOVERSIKT_CLIENTID
      value: "cd1456a1-b2cd-449d-8fc1-ffe55fe63b61"
    - name: SYFO_SYFOOVERSIKT_CLIENTID
      value: "4fca3a52-4540-4690-8a81-240ace253839"
    - name: SYFO_SMREG_CLIENTID
      value: "ab2d8ca9-7af1-45bb-af07-0f4793695e63"
    - name: SYFO_SMREG_NEW_CLIENTID
      value: "cd394576-33b3-4c71-8fe8-14ef7c78bb98"
    - name: SYFO_SMMANUELL_CLIENTID
      value: "b67cdfa3-437e-4d30-8a3f-8e0708125338"
    - name: SOSIALHJELP_MODIA_CLIENTID
      value: "6f661f36-1adb-42c3-9e10-294a10007880"
    - name: SPINNSYN_FRONTEND_INTERNE_CLIENTID
      value: "d9f767f1-89a0-413a-9c18-368eb3f752e9"
    - name: KAFKA_BROKERS_URL
      value: "a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443"
    - name: APP_ENVIRONMENT_NAME
      value: "p"
    - name: AAREG_URL
      value: "https://arbeid-og-inntekt.nais.adeo.no"
    - name: REDIS_HOST
      value: "modiacontextholder-redis.personoversikt.svc.nais.local"
