---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: modiacontextholder
  namespace: default
  labels:
    team: personoversikt
spec:
  image: "{{ image }}"
  port: 8080
  webproxy: true
  liveness:
    path: modiacontextholder/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: modiacontextholder/internal/metrics
  readiness:
    path: modiacontextholder/internal/isReady
    initialDelay: 50
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 768Mi
  ingresses:
    - https://modiacontextholder.nais.adeo.no/modiacontextholder
    - https://modapp.adeo.no/modiacontextholder
    - https://app.adeo.no/modiacontextholder
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvmodiacontextholder
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/prod/srvssolinux
        mountPath: /var/run/secrets/nais.io/srvssolinux
      - kvPath: /oracle/data/prod/creds/modiacontextholder-user
        mountPath: /var/run/secrets/nais.io/modiacontextholderDB
      - kvPath: /apikey/appdynamics/prod
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: SECURITY_TOKEN_SERVICE_DISCOVERY_URL
      value: "https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration"
    - name: SECURITYTOKENSERVICE_URL
      value: "https://sts.adeo.no/SecurityTokenServiceProvider/"
    - name: MODIACONTEXTHOLDERDB_URL
      value: "jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(CONNECT_TIMEOUT= 15)(RETRY_COUNT=20)(RETRY_DELAY=3)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=a01dbfl030.adeo.no)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=a01dbfl031.adeo.no)(PORT=1522)))(CONNECT_DATA=(SERVICE_NAME=modiacontextholder_ha)))"
    - name: MODIACONTEXTHOLDERDB_OEMENDPOINT
      value: "/em/cloud/dbaas/pluggabledbplatforminstance/byrequest/161"
    - name: AXSYS_REST_API_URL
      value: "https://axsys.nais.adeo.no/api"
    - name: VIRKSOMHET_ORGANISASJONENHET_V2_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_ORGANISASJONENHET_V2_ENDPOINTURL
      value: "https://app.adeo.no/norg2/ws/OrganisasjonEnhet/v2"
    - name: VIRKSOMHET_ORGANISASJONENHET_V2_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/nav-organisasjonEnhet-v2-tjenestespesifikasjon/2.1.0/nav-organisasjonEnhet-v2-tjenestespesifikasjon-2.1.0.zip"
    - name: LDAP_BASEDN
      value: "dc=adeo,dc=no"
    - name: LDAP_URL
      value: "ldaps://ldapgw.adeo.no"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=adeo,dc=no"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=adeo,dc=no"
    - name: LDAP_DOMAIN
      value: "ADEO.NO"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.adeo.no/api/"
    - name: ISSO_CLIENT_ID
      value: "veilarblogin-p"
    - name: FPSAK_CLIENT_ID
      value: "fpsak-frontend-p"
    - name: ISSO_DISCOVERY_URL
      value: "https://isso.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: ISSO_REFRESH_URL
      value: "https://app.adeo.no/veilarblogin/api/openam-refresh"
    - name: LOGINSERVICE_OIDC_DISCOVERYURI
      value: "https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration"
    - name: LOGINSERVICE_OIDC_CLIENTID
      value: "9b4e07a3-4f4c-4bab-b866-87f62dff480d"
    - name: KAFKA_BROKERS_URL
      value: "a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443"
    - name: APP_ENVIRONMENT_NAME
      value: "p"
    - name: PDL_API_URL
      value: "https://pdl-api.nais.adeo.no/graphql"
