---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: modiacontextholder
  namespace: personoversikt
  labels:
    team: personoversikt
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

    config.linkerd.io/proxy-cpu-limit: "1"
    config.linkerd.io/proxy-cpu-request: "200m"
    config.linkerd.io/proxy-memory-limit: "1Gi"
    config.linkerd.io/proxy-memory-request: "256Mi"
spec:
  image: "{{ image }}"
  port: 4000
  liveness:
    path: internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  readiness:
    path: internal/isReady
    initialDelay: 50
    periodSeconds: 10
    timeout: 1
  resources:
    limits:
      memory: 3072Mi
    requests:
      cpu: 250m
      memory: 1800Mi
  ingresses:
    - https://modiacontextholder.intern.nav.no
    - https://modiacontextholder.ansatt.nav.no
  replicas:
    min: 2
    max: 6
    scalingStrategy:
      cpu:
        thresholdPercentage: 80
  valkey:
    - instance: contextholder
      access: readwrite
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    outbound:
      external:
        - host: personoversikt-unleash-api.nav.cloud.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: graph.microsoft.com
      rules:
        - application: nom-api
          namespace: nom
          cluster: prod-gcp
        - application: norg2
          namespace: org
        - application: logging
          namespace: nais-system
    inbound:
      rules:
        - application: arbeidssokerregistrering-for-veileder
          cluster: prod-gcp
          namespace: paw
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: prod-gcp
        - application: beslutteroversikt
          namespace: obo
          cluster: prod-gcp
        - application: syfosmmanuell
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syk-dig
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: modiaflatefs
          namespace: personoversikt
          cluster: prod-fss
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: prod-gcp
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: prod-fss
        - application: rekrutteringsbistand-kandidatsok-api
          namespace: toi
          cluster: prod-gcp
        - application: rekrutteringsbistand
          namespace: toi
          cluster: prod-gcp
        - application: rekrutteringsbistand-frontend
          namespace: toi
        - application: spinnsyn-frontend-interne
          namespace: flex
          cluster: prod-gcp
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfomoteoversikt
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: sosialhjelp-modia-oidc-auth-proxy
          namespace: teamdigisos
          cluster: prod-fss
        - application: speil
          namespace: tbd
          cluster: prod-gcp
        - application: tiltaksgjennomforing-intern
          namespace: arbeidsgiver
          cluster: prod-gcp
        - application: tiltak-refusjon-saksbehandler
          namespace: arbeidsgiver
          cluster: prod-gcp
        - application: cv-veileder
          namespace: teampam
          cluster: prod-gcp
        - application: inngar
          namespace: dab
        - application: familie-integrasjoner
          namespace: teamfamilie
          cluster: prod-fss
        - application: nav-persondata-api
          namespace: holmes
          cluster: prod-gcp
        - application: gosys
          namespace: isa
          cluster: prod-fss
  envFrom:
    - secret: modiacontextholder-unleash-api-token
  env:
    - name: JAVA_TOOL_OPTIONS
      value: -XX:MaxRAMPercentage=60
    - name: PDL_API_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "prod-fss:pdl:pdl-api"
    - name: NORG2_API_URL
      value: "http://norg2.org/norg2"
    - name: NORG2_SCOPE
      value: "prod-gcp:org:norg2"
    - name: NOM_URL
      value: "http://nom-api.nom"
    - name: NOM_SCOPE
      value: "prod-gcp:nom:nom-api"
    - name: MS_GRAPH_URL
      value: "https://graph.microsoft.com/"
    - name: MS_GRAPH_SCOPE
      value: "https://graph.microsoft.com/.default"
    - name: APP_ENVIRONMENT_NAME
      value: "p"
    - name: AAREG_URL
      value: "https://arbeid-og-inntekt.prod-fss-pub.nais.io"
    - name: AAREG_PUBLIC_URL
      value: "https://arbeid-og-inntekt.nais.adeo.no"
    - name: SALESFORCE_URL
      value: "https://navdialog.lightning.force.com"
    - name: UNLEASH_ENVIRONMENT
      value: "production"
