---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: modiacontextholder-{{ namespace }}
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  envFrom:
    - secret: modiacontextholder-unleash-api-token
    - secret: modiacontextholder-redis-passord
  image: "{{ image }}"
  port: 8080
  webproxy: true
  liveness:
    path: modiacontextholder/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: modiacontextholder/internal/prometheus
  readiness:
    path: modiacontextholder/internal/isReady
    initialDelay: 50
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 768Mi
  ingresses:
    - https://modiacontextholder-{{ namespace }}.dev-fss-pub.nais.io/modiacontextholder
    - https://modiacontextholder-{{ namespace }}.dev.intern.nav.no/modiacontextholder
    - https://modiacontextholder-{{ namespace }}.nais.preprod.local/modiacontextholder
    - https://modiacontextholder-{{ namespace }}.dev.adeo.no/modiacontextholder
    - https://modapp-{{ namespace }}.adeo.no/modiacontextholder
    - https://app-{{ namespace }}.adeo.no/modiacontextholder
    - https://app-{{ namespace }}.dev.adeo.no/modiacontextholder
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvmodiacontextholder
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/dev/srvssolinux
        mountPath: /var/run/secrets/nais.io/srvssolinux
      - kvPath: /oracle/data/dev/creds/modiacontextholder_{{ namespace }}-user
        mountPath: /var/run/secrets/nais.io/modiacontextholderDB
      - kvPath: /oracle/data/dev/config/modiacontextholder_{{ namespace }}
        mountPath: /var/run/secrets/nais.io/db_config
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    outbound:
      external:
        - host: personoversikt-unleash-api.nav.cloud.nais.io
    inbound:
      rules:
        - application: arbeidssokerregistrering-veileder
          namespace: paw
          cluster: dev-gcp
        - application: arbeidssokerregistrering-for-veileder
          cluster: dev-gcp
          namespace: paw
        - application: veilarbpersonflate
          namespace: poao
          cluster: dev-gcp
        - application: veilarbportefoljeflatefs
          namespace: obo
          cluster: dev-gcp
        - application: beslutteroversikt
          namespace: obo
          cluster: dev-gcp
        - application: smregistrering
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmmanuell
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syk-dig
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: modiaflatefs-{{ namespace }}
          namespace: personoversikt
          cluster: dev-fss
        - application: modiapersonoversikt-{{ namespace }}
          namespace: personoversikt
          cluster: dev-fss
        - application: rekrutteringsbistand-container
          namespace: toi
          cluster: dev-gcp
        - application: rekrutteringsbistand
          namespace: toi
          cluster: dev-gcp
        - application: spinnsyn-frontend-interne
          namespace: flex
          cluster: dev-gcp
        - application: finnfastlege
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfomoteoversikt
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfooversikt
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: sosialhjelp-modia-oidc-auth-proxy
          namespace: teamdigisos
          cluster: dev-fss
        - application: speil
          namespace: tbd
          cluster: dev-gcp
  secureLogs:
    enabled: true
  env:
    - name: AXSYS_URL
      value: "https://axsys.dev.intern.nav.no"
    - name: AXSYS_SCOPE
      value: "dev-fss:org:axsys"
    - name: PDL_API_URL
      value: "https://pdl-api-{{ namespace }}.dev.intern.nav.no/graphql"
    - name: PDL_SCOPE
      value: "dev-fss:pdl:pdl-api-{{ namespace }}"
    - name: NORG2_API_URL
      value: "https://app-{{ namespace }}.adeo.no/norg2"
    - name: NOM_URL
      value: "https://nom-api.intern.dev.nav.no"
    - name: NOM_SCOPE
      value: "dev-gcp:nom:nom-api"
    - name: MS_GRAPH_URL
      value: "https://graph.microsoft.com/"
    - name: MS_GRAPH_SCOPE
      value: "https://graph.microsoft.com/.default"
    - name: LOGINSERVICE_OIDC_DISCOVERYURI
      value: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration"
    - name: AAD_V2_DISCOVERURI
      value: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration"
    - name: LOGINSERVICE_OIDC_CLIENTID
      value: "38e07d31-659d-4595-939a-f18dce3446c5"
    - name: APP_ENVIRONMENT_NAME
      value: "{{ namespace }}"
    - name: AAREG_URL
      value: "https://arbeid-og-inntekt-q1.dev.adeo.no"
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_HOST
      value: "modiacontextholder-redis-med-passord.personoversikt.svc.nais.local"
    - name: SALESFORCE_URL
      value: "https://navdialog--sit2.lightning.force.com"
    - name: UNLEASH_ENVIRONMENT
      value: "development"
