---
kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: modiacontextholder-{{ namespace }}
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{ image }}"
  port: 8080
  webproxy: true
  liveness:
    path: modiacontextholder/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: modiacontextholder/internal/prometheus
  readiness:
    path: modiacontextholder/internal/isReady
    initialDelay: 50
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 400m
      memory: 768Mi
  ingresses:
    - https://modiacontextholder-{{ namespace }}.dev-fss-pub.nais.io/modiacontextholder
    - https://modiacontextholder-{{ namespace }}.dev.intern.nav.no/modiacontextholder
    - https://modiacontextholder-{{ namespace }}.nais.preprod.local/modiacontextholder
    - https://modiacontextholder-{{ namespace }}.dev.adeo.no/modiacontextholder
    - https://modapp-{{ namespace }}.adeo.no/modiacontextholder
    - https://app-{{ namespace }}.adeo.no/modiacontextholder
    - https://app-{{ namespace }}.dev.adeo.no/modiacontextholder
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvmodiacontextholder
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/dev/srvssolinux
        mountPath: /var/run/secrets/nais.io/srvssolinux
      - kvPath: /oracle/data/dev/creds/modiacontextholder_{{ namespace }}-user
        mountPath: /var/run/secrets/nais.io/modiacontextholderDB
      - kvPath: /oracle/data/dev/config/modiacontextholder_{{ namespace }}
        mountPath: /var/run/secrets/nais.io/db_config
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: arbeidssokerregistrering-veileder
          namespace: paw
          cluster: dev-gcp
  secureLogs:
    enabled: true
  env:
    - name: SECURITY_TOKEN_SERVICE_DISCOVERY_URL
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration"
    - name: AXSYS_REST_API_URL
      value: "https://axsys.nais.preprod.local"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.io/api/"
    - name: PDL_API_URL
      value: "https://pdl-api-{{ namespace }}.dev.intern.nav.no/graphql"
    - name: NORG2_API_URL
      value: "https://app-{{ namespace }}.adeo.no/norg2"
    - name: LDAP_BASEDN
      value: "dc=preprod,dc=local"
    - name: LDAP_URL
      value: "ldaps://ldapgw.preprod.local"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=preprod,dc=local"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=preprod,dc=local"
    - name: LDAP_DOMAIN
      value: "PREPROD.LOCAL"
    - name: MS_GRAPH_CLIENT_URL
      value: "https://graph.microsoft.com/v1.0"
    - name: ISSO_CLIENT_ID
      value: "veilarblogin-{{ namespace }}"
    - name: MODIA_CLIENT_ID
      value: "modialogin-{{ namespace }}"
    - name: FPSAK_CLIENT_ID
      value: "fpsak-frontend-{{ namespace }}"
    - name: ISSO_DISCOVERY_URL
      value: "https://isso-q.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: LOGINSERVICE_OIDC_DISCOVERYURI
      value: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/.well-known/openid-configuration"
    - name: AAD_V2_DISCOVERURI
      value: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration"
    - name: LOGINSERVICE_OIDC_CLIENTID
      value: "38e07d31-659d-4595-939a-f18dce3446c5"
    - name: VEILARBLOGIN_AAD_CLIENT_ID
      value: "2edd96a2-fb5a-4dfa-8f36-848ae306f9b1"
    - name: SYFO_FINNFASTLEGE_CLIENTID
      value: "decdb625-ddde-4c4a-9586-f20862b9e1fe"
    - name: SYFO_SYFOMODIAPERSON_CLIENTID
      value: "c65ad33c-2f8a-4b2c-9160-95a4c18562b0"
    - name: SYFO_SYFOMOTEOVERSIKT_CLIENTID
      value: "5bfe761b-8fcb-4b89-81a0-f37bee456af5"
    - name: SYFO_SYFOOVERSIKT_CLIENTID
      value: "6db2c887-7c46-49a8-a6a5-26adec81a145"
    - name: SYFO_SMREG_CLIENTID
      value: "6d29c845-6662-4c2c-a3b8-46a1e1967855"
    - name: SYFO_SMREG_NEW_CLIENTID
      value: "45530b4a-b360-4eeb-a8dc-0d5100b7877c"
    - name: SYFO_SMMANUELL_CLIENTID
      value: "9f5e5e25-248b-4931-9645-433b845b1a83"
    - name: SOSIALHJELP_MODIA_CLIENTID
      value: "6f661f36-1adb-42c3-9e10-294a10007880"
    - name: SPINNSYN_FRONTEND_INTERNE_CLIENTID
      value: "300fd59d-c575-473a-bd6a-9b0fd51b28ad"
    - name: REKRUTTERINGSBISTAND_CONTAINER_CLIENTID
      value: "19069abf-30aa-4a8d-90fd-caaacdc45166"
    - name: APP_ENVIRONMENT_NAME
      value: "{{ namespace }}"
    - name: AAREG_URL
      value: "https://arbeid-og-inntekt-q1.dev.adeo.no"
    - name: REDIS_HOST
      value: "modiacontextholder-redis.personoversikt.svc.nais.local"
