---
apiVersion: "nais.io/v1alpha1"
kind: Redis
metadata:
  labels:
    team: personoversikt
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "999"
  name: modiacontextholder-redis-personoversikt
  namespace: personoversikt
spec:
  image: redis:<redis:6-alpine> # or a custom Redis-image
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1 # More replicas doesn't sync
  resources: # you need to monitor the resource usage yourself
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis