name: Setup Redis application

on:
  push:
    paths:
      - '.github/workflows/redis.yaml'
      - '.nais/redis.yaml'

env:
  CI: true
  TZ: Europe/Oslo

jobs:
  setup-redis:
    name: Setup Redis application
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup preprod
        if: github.ref == 'refs/heads/dev'
        uses: nais/deploy/actions/deploy@v2
        env:
          PRINT_PAYLOAD: true
          CLUSTER: dev-fss
          RESOURCE: .nais/redis.yaml
      - name: Setup prod
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v2
        env:
          PRINT_PAYLOAD: true
          CLUSTER: prod-fss
          RESOURCE: .nais/redis.yaml