name: Setup Redis application with password

on:
  push:
    paths:
      - '.github/workflows/redis-med-passord.yaml'
      - '.nais/redis-med-passord.yaml'

env:
  CI: true
  TZ: Europe/Oslo

jobs:
  setup-redis:
    name: Setup Redis application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup preprod
        if: github.ref == 'refs/heads/dev'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          PRINT_PAYLOAD: true
          CLUSTER: dev-fss
          RESOURCE: .nais/redis-med-passord.yaml
      - name: Setup prod
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          PRINT_PAYLOAD: true
          CLUSTER: prod-fss
          RESOURCE: .nais/redis-med-passord.yaml