name: Setup Valkey instance

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/valkey.yaml'
      - '.nais/valkey-*.yaml'

env:
  CI: true
  TZ: Europe/Oslo

jobs:
  deploy:
    name: Setup Valkey
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        env: [ dev-gcp, prod-gcp ]
    environment: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup ${{ matrix.env }}
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          PRINT_PAYLOAD: true
          CLUSTER: ${{ matrix.env }}
          RESOURCE: .nais/valkey-${{matrix.env}}.yaml
